window.APP_I18N = {
    en: {
        pageTitle: "Apps & Games — Free Online Apps and Games",
        pageDescription: "Discover free online apps and browser games including Digital Clock, Date Lotto Generator, Emoji Copy & Paste, Unit Converter, Tetris, UFO Invaders and Phoenix Arcade.",
        homeLabel: "Apps & Games Home", navLabel: "Main navigation", navApps: "Apps", navGames: "Games", navInfo: "Info",
        languageLabel: "Language", selectLanguage: "Select language", themeLabel: "Toggle theme",
        heroSubtitle: "Free Online Apps and Games",
        heroText: "Discover practical browser apps and fun games in one place. Open them instantly without installing extra software or creating an account. The collection is designed for quick, simple access on desktop, tablet and mobile browsers.",
        exploreApps: "Explore Apps", playGames: "Play Games",
        appsLabel: "📱 APPS", appsHeading: "Useful Online Apps",
        appsText: "Open practical browser apps for everyday use. Current projects include Digital Clock, Date Lotto Generator, Emoji Copy & Paste and Unit Converter, with more apps planned as the collection grows.",
        gamesLabel: "🎮 GAMES", gamesHeading: "Browser Games You Can Play Instantly",
        gamesText: "Choose from puzzle and arcade-style games and start playing directly in your browser. The current collection includes Tetris, UFO Invaders: Neon Defense and Phoenix Arcade.",
        aboutLabel: "ABOUT APPS & GAMES", aboutHeading: "Free Browser Projects in One Place",
        aboutText1: "Apps & Games is an independent collection of browser-based apps and games published under the Soldatix name. The goal is simple: provide useful small apps and entertaining games that are easy to open, understand and use.",
        aboutText2: "Instead of requiring a separate installation, the projects are designed to run online in a web browser whenever possible. The collection combines practical apps such as Digital Clock, Date Lotto Generator, Emoji Copy & Paste and Unit Converter with browser games such as Tetris, UFO Invaders: Neon Defense and Phoenix Arcade.",
        aboutText3: "Each project is developed as a standalone experience with a focus on clear controls, responsive layouts and straightforward navigation. New apps, games and improvements can be added over time while existing projects continue to receive fixes and usability updates.",
        expectHeading: "What you can expect", expect1: "Free access to the available browser apps and games.", expect2: "No Apps & Games account required to start using the projects.", expect3: "Fast access from modern desktop, tablet and mobile browsers.", expect4: "Clear descriptions so you know what each project does before opening it.", expect5: "Ongoing improvements, compatibility fixes and new projects over time.",
        faqHeading: "Frequently Asked Questions", faqQ1: "Are the apps and games free to use?", faqA1: "Yes. The apps and games listed on Apps & Games are free to use. Donations are optional and help support development and the project.", faqQ2: "Do I need to create an account?", faqA2: "No. You can open the available apps and games without creating an Apps & Games account.", faqQ3: "Do I need to install anything?", faqA3: "No. The projects are designed to run directly in a compatible modern web browser. Some projects may also offer browser installation features such as a home-screen shortcut or PWA support.", faqQ4: "Does Date Lotto Generator predict winning lottery numbers?", faqA4: "No. Date Lotto Generator creates repeatable number combinations from the selected date and your chosen settings. Lottery drawings are random, so the app cannot predict results or guarantee a win.", faqQ5: "Can I use the site on a phone or tablet?", faqA5: "Most projects are designed for modern desktop and mobile browsers. The exact layout and performance can vary depending on screen size, browser version and device capabilities.", faqQ6: "Does Apps & Games use analytics or advertising?", faqA6: "The website uses Google Analytics to understand site usage and may use Google AdSense for advertising. More information is available in the", privacyPolicy: "Privacy Policy",
        supportLabel: "ℹ INFO & SUPPORT", supportHeading: "Support the Project", supportText1: "The apps and games are free to use, but voluntary donations are welcome.", supportText2: "A part of the received donations will be forwarded to various charitable organizations. The largest part will be donated to institutions caring for children without adequate parental care.",
        donateHeading: "You can make donations to:", paypalHeading: "PayPal account", paypalText: "Support the project securely through PayPal.", openPayPal: "Open PayPal ↗", stripeHeading: "Card Payment (Stripe)", stripeText: "Donate securely using your credit or debit card.", openStripe: "Open Stripe ↗", cryptoHeading: "Crypto Wallet", cryptoText: "You can also support the project using cryptocurrency.",
        copy: "Copy", copied: "Copied!", copyFailed: "Failed", learnMore: "LEARN MORE →", openApp: "OPEN APP →", playGame: "PLAY GAME →", appBadge: "APP", gameBadge: "GAME", live: "LIVE",
        footerAbout: "About", footerSupport: "Support"
    },
    hr: {
        pageTitle: "Apps & Games — besplatne online aplikacije i igre",
        pageDescription: "Otkrijte besplatne online aplikacije i igre za preglednik, uključujući Digital Clock, Date Lotto Generator, Emoji Copy & Paste, Unit Converter, Tetris, UFO Invaders i Phoenix Arcade.",
        homeLabel: "Početna stranica Apps & Games", navLabel: "Glavna navigacija", navApps: "Aplikacije", navGames: "Igre", navInfo: "Info",
        languageLabel: "Jezik", selectLanguage: "Odaberi jezik", themeLabel: "Promijeni temu",
        heroSubtitle: "Besplatne online aplikacije i igre",
        heroText: "Otkrijte praktične aplikacije za preglednik i zabavne igre na jednom mjestu. Otvorite ih odmah, bez instaliranja dodatnog softvera i otvaranja računa. Kolekcija je prilagođena brzom i jednostavnom pristupu na računalu, tabletu i mobitelu.",
        exploreApps: "Istraži aplikacije", playGames: "Igraj igre",
        appsLabel: "📱 APLIKACIJE", appsHeading: "Korisne online aplikacije",
        appsText: "Otvorite praktične aplikacije za svakodnevnu uporabu. Trenutačni projekti uključuju Digital Clock, Date Lotto Generator, Emoji Copy & Paste i Unit Converter, a kolekciji ćemo dodavati nove aplikacije.",
        gamesLabel: "🎮 IGRE", gamesHeading: "Igre koje možete odmah igrati",
        gamesText: "Odaberite slagalice ili arkadne igre i odmah ih pokrenite u pregledniku. Trenutačna kolekcija uključuje Tetris, UFO Invaders: Neon Defense i Phoenix Arcade.",
        aboutLabel: "O APPS & GAMES", aboutHeading: "Besplatni projekti za preglednik na jednom mjestu",
        aboutText1: "Apps & Games je neovisna kolekcija aplikacija i igara za preglednik objavljenih pod imenom Soldatix. Cilj je jednostavan: ponuditi korisne male aplikacije i zabavne igre koje je lako otvoriti, razumjeti i koristiti.",
        aboutText2: "Umjesto zasebne instalacije, projekti su napravljeni tako da se, kad god je moguće, pokreću online u web-pregledniku. Kolekcija spaja praktične aplikacije kao što su Digital Clock, Date Lotto Generator, Emoji Copy & Paste i Unit Converter s igrama Tetris, UFO Invaders: Neon Defense i Phoenix Arcade.",
        aboutText3: "Svaki je projekt izrađen kao samostalno iskustvo s jasnim kontrolama, prilagodljivim prikazom i jednostavnom navigacijom. S vremenom se mogu dodavati nove aplikacije, igre i poboljšanja, dok postojeći projekti dobivaju popravke i nadogradnje upotrebljivosti.",
        expectHeading: "Što možete očekivati", expect1: "Besplatan pristup dostupnim aplikacijama i igrama za preglednik.", expect2: "Za korištenje projekata nije potreban Apps & Games račun.", expect3: "Brz pristup iz modernih preglednika na računalu, tabletu i mobitelu.", expect4: "Jasni opisi kako biste prije otvaranja znali čemu svaki projekt služi.", expect5: "Stalna poboljšanja, popravci kompatibilnosti i novi projekti.",
        faqHeading: "Često postavljana pitanja", faqQ1: "Jesu li aplikacije i igre besplatne?", faqA1: "Da. Aplikacije i igre navedene na Apps & Games besplatne su za korištenje. Donacije nisu obvezne, ali pomažu razvoju i održavanju projekta.", faqQ2: "Moram li otvoriti račun?", faqA2: "Ne. Dostupne aplikacije i igre možete otvoriti bez stvaranja Apps & Games računa.", faqQ3: "Moram li nešto instalirati?", faqA3: "Ne. Projekti su napravljeni za izravno pokretanje u kompatibilnom modernom web-pregledniku. Neki projekti mogu nuditi i mogućnosti instalacije u pregledniku, poput prečaca na početnom zaslonu ili PWA podrške.", faqQ4: "Predviđa li Date Lotto Generator dobitne brojeve?", faqA4: "Ne. Date Lotto Generator izrađuje ponovljive kombinacije brojeva iz odabranog datuma i postavki. Loto izvlačenja su nasumična pa aplikacija ne može predvidjeti rezultate ni jamčiti dobitak.", faqQ5: "Mogu li stranicu koristiti na mobitelu ili tabletu?", faqA5: "Većina projekata prilagođena je modernim preglednicima na računalu i mobilnim uređajima. Prikaz i rad mogu se razlikovati ovisno o veličini zaslona, verziji preglednika i mogućnostima uređaja.", faqQ6: "Koristi li Apps & Games analitiku ili oglase?", faqA6: "Stranica koristi Google Analytics za razumijevanje načina korištenja i može prikazivati oglase putem Google AdSensea. Više informacija nalazi se u dokumentu", privacyPolicy: "Pravila privatnosti",
        supportLabel: "ℹ INFO I PODRŠKA", supportHeading: "Podržite projekt", supportText1: "Aplikacije i igre besplatne su za korištenje, ali dobrovoljne donacije su dobrodošle.", supportText2: "Dio primljenih donacija proslijedit će se različitim humanitarnim organizacijama. Najveći dio bit će doniran ustanovama koje se skrbe o djeci bez odgovarajuće roditeljske skrbi.",
        donateHeading: "Donirati možete putem:", paypalHeading: "PayPal račun", paypalText: "Sigurno podržite projekt putem PayPala.", openPayPal: "Otvori PayPal ↗", stripeHeading: "Plaćanje karticom (Stripe)", stripeText: "Sigurno donirajte kreditnom ili debitnom karticom.", openStripe: "Otvori Stripe ↗", cryptoHeading: "Kripto novčanik", cryptoText: "Projekt možete podržati i kriptovalutama.",
        copy: "Kopiraj", copied: "Kopirano!", copyFailed: "Neuspjelo", learnMore: "SAZNAJ VIŠE →", openApp: "OTVORI APLIKACIJU →", playGame: "IGRAJ →", appBadge: "APP", gameBadge: "IGRA", live: "AKTIVNO",
        footerAbout: "O projektu", footerSupport: "Podrška"
    },
    de: {
        pageTitle: "Apps & Games — kostenlose Online-Apps und Spiele",
        pageDescription: "Entdecke kostenlose Online-Apps und Browserspiele wie Digital Clock, Date Lotto Generator, Emoji Copy & Paste, Unit Converter, Tetris, UFO Invaders und Phoenix Arcade.",
        homeLabel: "Apps & Games Startseite", navLabel: "Hauptnavigation", navApps: "Apps", navGames: "Spiele", navInfo: "Info",
        languageLabel: "Sprache", selectLanguage: "Sprache auswählen", themeLabel: "Design wechseln",
        heroSubtitle: "Kostenlose Online-Apps und Spiele",
        heroText: "Entdecke praktische Browser-Apps und unterhaltsame Spiele an einem Ort. Öffne sie sofort, ohne zusätzliche Software zu installieren oder ein Konto anzulegen. Die Sammlung ermöglicht einen schnellen und einfachen Zugriff am Computer, Tablet und Smartphone.",
        exploreApps: "Apps entdecken", playGames: "Spiele spielen",
        appsLabel: "📱 APPS", appsHeading: "Nützliche Online-Apps", appsText: "Öffne praktische Browser-Apps für den Alltag. Zu den aktuellen Projekten gehören Digital Clock, Date Lotto Generator, Emoji Copy & Paste und Unit Converter. Weitere Apps sind geplant.",
        gamesLabel: "🎮 SPIELE", gamesHeading: "Browserspiele zum sofortigen Spielen", gamesText: "Wähle Puzzle- oder Arcade-Spiele und spiele direkt im Browser. Die aktuelle Sammlung umfasst Tetris, UFO Invaders: Neon Defense und Phoenix Arcade.",
        aboutLabel: "ÜBER APPS & GAMES", aboutHeading: "Kostenlose Browser-Projekte an einem Ort", aboutText1: "Apps & Games ist eine unabhängige Sammlung von Browser-Apps und -Spielen, die unter dem Namen Soldatix veröffentlicht wird. Das Ziel ist einfach: nützliche kleine Apps und unterhaltsame Spiele anzubieten, die leicht zu öffnen, zu verstehen und zu verwenden sind.", aboutText2: "Statt einer separaten Installation laufen die Projekte nach Möglichkeit online im Webbrowser. Die Sammlung verbindet praktische Apps wie Digital Clock, Date Lotto Generator, Emoji Copy & Paste und Unit Converter mit Spielen wie Tetris, UFO Invaders: Neon Defense und Phoenix Arcade.", aboutText3: "Jedes Projekt wird als eigenständiges Erlebnis mit klarer Steuerung, anpassungsfähigem Layout und einfacher Navigation entwickelt. Neue Apps, Spiele und Verbesserungen können jederzeit ergänzt werden, während bestehende Projekte weiterhin Fehlerbehebungen und Bedienungsverbesserungen erhalten.",
        expectHeading: "Das kannst du erwarten", expect1: "Kostenloser Zugang zu den verfügbaren Browser-Apps und Spielen.", expect2: "Kein Apps-&-Games-Konto erforderlich.", expect3: "Schneller Zugriff mit modernen Browsern auf Computer, Tablet und Smartphone.", expect4: "Klare Beschreibungen, damit du vor dem Öffnen weisst, was ein Projekt bietet.", expect5: "Laufende Verbesserungen, Kompatibilitätskorrekturen und neue Projekte.",
        faqHeading: "Häufig gestellte Fragen", faqQ1: "Sind die Apps und Spiele kostenlos?", faqA1: "Ja. Die auf Apps & Games aufgeführten Apps und Spiele können kostenlos verwendet werden. Spenden sind freiwillig und unterstützen die Entwicklung und das Projekt.", faqQ2: "Muss ich ein Konto erstellen?", faqA2: "Nein. Du kannst die verfügbaren Apps und Spiele ohne Apps-&-Games-Konto öffnen.", faqQ3: "Muss ich etwas installieren?", faqA3: "Nein. Die Projekte laufen direkt in einem kompatiblen modernen Webbrowser. Einige Projekte bieten möglicherweise auch Browser-Installationsfunktionen wie eine Verknüpfung auf dem Startbildschirm oder PWA-Unterstützung.", faqQ4: "Sagt der Date Lotto Generator Gewinnzahlen voraus?", faqA4: "Nein. Der Date Lotto Generator erstellt wiederholbare Zahlenkombinationen aus dem gewählten Datum und den Einstellungen. Lottoziehungen sind zufällig; die App kann keine Ergebnisse vorhersagen oder einen Gewinn garantieren.", faqQ5: "Kann ich die Seite auf dem Smartphone oder Tablet nutzen?", faqA5: "Die meisten Projekte sind für moderne Desktop- und Mobilbrowser ausgelegt. Darstellung und Leistung können je nach Bildschirmgrösse, Browserversion und Gerätefunktionen variieren.", faqQ6: "Verwendet Apps & Games Analysen oder Werbung?", faqA6: "Die Website verwendet Google Analytics, um die Nutzung zu verstehen, und kann Werbung über Google AdSense anzeigen. Weitere Informationen findest du in der", privacyPolicy: "Datenschutzerklärung",
        supportLabel: "ℹ INFO & UNTERSTÜTZUNG", supportHeading: "Projekt unterstützen", supportText1: "Die Apps und Spiele sind kostenlos, freiwillige Spenden sind jedoch willkommen.", supportText2: "Ein Teil der eingegangenen Spenden wird an verschiedene gemeinnützige Organisationen weitergeleitet. Der grösste Teil wird Einrichtungen gespendet, die Kinder ohne angemessene elterliche Betreuung versorgen.", donateHeading: "Spendenmöglichkeiten:", paypalHeading: "PayPal-Konto", paypalText: "Unterstütze das Projekt sicher über PayPal.", openPayPal: "PayPal öffnen ↗", stripeHeading: "Kartenzahlung (Stripe)", stripeText: "Spende sicher mit Kredit- oder Debitkarte.", openStripe: "Stripe öffnen ↗", cryptoHeading: "Krypto-Wallet", cryptoText: "Du kannst das Projekt auch mit Kryptowährungen unterstützen.",
        copy: "Kopieren", copied: "Kopiert!", copyFailed: "Fehlgeschlagen", learnMore: "MEHR ERFAHREN →", openApp: "APP ÖFFNEN →", playGame: "SPIELEN →", appBadge: "APP", gameBadge: "SPIEL", live: "LIVE", footerAbout: "Über uns", footerSupport: "Unterstützung"
    },
    it: {
        pageTitle: "Apps & Games — applicazioni e giochi online gratuiti",
        pageDescription: "Scopri applicazioni online e giochi per browser gratuiti come Digital Clock, Date Lotto Generator, Emoji Copy & Paste, Unit Converter, Tetris, UFO Invaders e Phoenix Arcade.",
        homeLabel: "Pagina iniziale di Apps & Games", navLabel: "Navigazione principale", navApps: "App", navGames: "Giochi", navInfo: "Info", languageLabel: "Lingua", selectLanguage: "Seleziona la lingua", themeLabel: "Cambia tema",
        heroSubtitle: "Applicazioni e giochi online gratuiti", heroText: "Scopri pratiche applicazioni per browser e giochi divertenti in un unico posto. Aprili subito senza installare software aggiuntivo o creare un account. La raccolta è pensata per un accesso rapido e semplice da computer, tablet e smartphone.", exploreApps: "Scopri le app", playGames: "Gioca",
        appsLabel: "📱 APP", appsHeading: "Applicazioni online utili", appsText: "Apri pratiche applicazioni per l'uso quotidiano. I progetti attuali includono Digital Clock, Date Lotto Generator, Emoji Copy & Paste e Unit Converter, con nuove app previste in futuro.", gamesLabel: "🎮 GIOCHI", gamesHeading: "Giochi per browser da avviare subito", gamesText: "Scegli tra rompicapi e giochi arcade e gioca direttamente nel browser. La raccolta attuale include Tetris, UFO Invaders: Neon Defense e Phoenix Arcade.",
        aboutLabel: "INFORMAZIONI SU APPS & GAMES", aboutHeading: "Progetti gratuiti per browser in un unico posto", aboutText1: "Apps & Games è una raccolta indipendente di applicazioni e giochi per browser pubblicati con il nome Soldatix. L'obiettivo è semplice: offrire piccole app utili e giochi divertenti, facili da aprire, comprendere e utilizzare.", aboutText2: "Senza richiedere un'installazione separata, i progetti sono pensati per funzionare online in un browser quando possibile. La raccolta unisce app pratiche come Digital Clock, Date Lotto Generator, Emoji Copy & Paste e Unit Converter a giochi come Tetris, UFO Invaders: Neon Defense e Phoenix Arcade.", aboutText3: "Ogni progetto è sviluppato come esperienza indipendente, con comandi chiari, layout adattabili e navigazione semplice. Nel tempo potranno essere aggiunti nuove app, giochi e miglioramenti, mentre i progetti esistenti continueranno a ricevere correzioni e aggiornamenti di usabilità.",
        expectHeading: "Cosa puoi aspettarti", expect1: "Accesso gratuito alle applicazioni e ai giochi disponibili.", expect2: "Nessun account Apps & Games necessario.", expect3: "Accesso rapido dai browser moderni su computer, tablet e smartphone.", expect4: "Descrizioni chiare per capire ogni progetto prima di aprirlo.", expect5: "Miglioramenti continui, correzioni di compatibilità e nuovi progetti.",
        faqHeading: "Domande frequenti", faqQ1: "Le applicazioni e i giochi sono gratuiti?", faqA1: "Sì. Le applicazioni e i giochi elencati su Apps & Games sono gratuiti. Le donazioni sono facoltative e aiutano a sostenere lo sviluppo e il progetto.", faqQ2: "Devo creare un account?", faqA2: "No. Puoi aprire le applicazioni e i giochi disponibili senza creare un account Apps & Games.", faqQ3: "Devo installare qualcosa?", faqA3: "No. I progetti funzionano direttamente in un browser moderno compatibile. Alcuni progetti possono offrire anche funzioni di installazione dal browser, come una scorciatoia nella schermata iniziale o il supporto PWA.", faqQ4: "Date Lotto Generator prevede i numeri vincenti?", faqA4: "No. Date Lotto Generator crea combinazioni ripetibili a partire dalla data selezionata e dalle impostazioni. Le estrazioni sono casuali, quindi l'app non può prevedere i risultati né garantire una vincita.", faqQ5: "Posso usare il sito su smartphone o tablet?", faqA5: "La maggior parte dei progetti è pensata per browser moderni desktop e mobili. Layout e prestazioni possono variare in base alle dimensioni dello schermo, alla versione del browser e alle caratteristiche del dispositivo.", faqQ6: "Apps & Games utilizza statistiche o pubblicità?", faqA6: "Il sito utilizza Google Analytics per comprendere l'utilizzo e può mostrare pubblicità tramite Google AdSense. Maggiori informazioni sono disponibili nella", privacyPolicy: "Informativa sulla privacy",
        supportLabel: "ℹ INFO E SUPPORTO", supportHeading: "Sostieni il progetto", supportText1: "Le applicazioni e i giochi sono gratuiti, ma le donazioni volontarie sono benvenute.", supportText2: "Una parte delle donazioni ricevute sarà destinata a diverse organizzazioni benefiche. La parte maggiore sarà donata a istituti che si occupano di bambini senza un'adeguata assistenza genitoriale.", donateHeading: "Puoi effettuare una donazione tramite:", paypalHeading: "Conto PayPal", paypalText: "Sostieni il progetto in modo sicuro tramite PayPal.", openPayPal: "Apri PayPal ↗", stripeHeading: "Pagamento con carta (Stripe)", stripeText: "Dona in modo sicuro con carta di credito o di debito.", openStripe: "Apri Stripe ↗", cryptoHeading: "Portafoglio crypto", cryptoText: "Puoi sostenere il progetto anche con criptovalute.",
        copy: "Copia", copied: "Copiato!", copyFailed: "Errore", learnMore: "SCOPRI DI PIÙ →", openApp: "APRI L'APP →", playGame: "GIOCA →", appBadge: "APP", gameBadge: "GIOCO", live: "ATTIVO", footerAbout: "Chi siamo", footerSupport: "Supporto"
    },
    es: {
        pageTitle: "Apps & Games — aplicaciones y juegos online gratis",
        pageDescription: "Descubre aplicaciones online y juegos de navegador gratuitos como Digital Clock, Date Lotto Generator, Emoji Copy & Paste, Unit Converter, Tetris, UFO Invaders y Phoenix Arcade.",
        homeLabel: "Inicio de Apps & Games", navLabel: "Navegación principal", navApps: "Apps", navGames: "Juegos", navInfo: "Info", languageLabel: "Idioma", selectLanguage: "Seleccionar idioma", themeLabel: "Cambiar tema",
        heroSubtitle: "Aplicaciones y juegos online gratis", heroText: "Descubre aplicaciones prácticas para el navegador y juegos divertidos en un solo lugar. Ábrelos al instante sin instalar software adicional ni crear una cuenta. La colección está diseñada para un acceso rápido y sencillo desde ordenador, tableta y móvil.", exploreApps: "Explorar apps", playGames: "Jugar",
        appsLabel: "📱 APPS", appsHeading: "Aplicaciones online útiles", appsText: "Abre aplicaciones prácticas para el uso diario. Los proyectos actuales incluyen Digital Clock, Date Lotto Generator, Emoji Copy & Paste y Unit Converter, y se añadirán más apps a medida que crezca la colección.", gamesLabel: "🎮 JUEGOS", gamesHeading: "Juegos de navegador para jugar al instante", gamesText: "Elige entre puzles y juegos arcade y empieza a jugar directamente en el navegador. La colección actual incluye Tetris, UFO Invaders: Neon Defense y Phoenix Arcade.",
        aboutLabel: "ACERCA DE APPS & GAMES", aboutHeading: "Proyectos gratuitos para navegador en un solo lugar", aboutText1: "Apps & Games es una colección independiente de aplicaciones y juegos para navegador publicados con el nombre Soldatix. El objetivo es sencillo: ofrecer pequeñas apps útiles y juegos entretenidos que sean fáciles de abrir, entender y usar.", aboutText2: "Sin necesidad de una instalación independiente, los proyectos están diseñados para funcionar online en un navegador siempre que sea posible. La colección combina apps prácticas como Digital Clock, Date Lotto Generator, Emoji Copy & Paste y Unit Converter con juegos como Tetris, UFO Invaders: Neon Defense y Phoenix Arcade.", aboutText3: "Cada proyecto se desarrolla como una experiencia independiente centrada en controles claros, diseños adaptables y navegación sencilla. Con el tiempo se podrán añadir nuevas apps, juegos y mejoras, mientras que los proyectos existentes seguirán recibiendo correcciones y mejoras de uso.",
        expectHeading: "Qué puedes esperar", expect1: "Acceso gratuito a las aplicaciones y juegos disponibles.", expect2: "No necesitas una cuenta de Apps & Games.", expect3: "Acceso rápido desde navegadores modernos en ordenador, tableta y móvil.", expect4: "Descripciones claras para saber qué hace cada proyecto antes de abrirlo.", expect5: "Mejoras continuas, correcciones de compatibilidad y nuevos proyectos.",
        faqHeading: "Preguntas frecuentes", faqQ1: "¿Las aplicaciones y los juegos son gratuitos?", faqA1: "Sí. Las aplicaciones y los juegos de Apps & Games se pueden usar gratis. Las donaciones son opcionales y ayudan a mantener el desarrollo y el proyecto.", faqQ2: "¿Tengo que crear una cuenta?", faqA2: "No. Puedes abrir las aplicaciones y los juegos disponibles sin crear una cuenta de Apps & Games.", faqQ3: "¿Tengo que instalar algo?", faqA3: "No. Los proyectos funcionan directamente en un navegador moderno compatible. Algunos proyectos también pueden ofrecer funciones de instalación desde el navegador, como un acceso directo en la pantalla de inicio o compatibilidad con PWA.", faqQ4: "¿Date Lotto Generator predice los números ganadores?", faqA4: "No. Date Lotto Generator crea combinaciones repetibles a partir de la fecha seleccionada y la configuración. Los sorteos son aleatorios, por lo que la app no puede predecir resultados ni garantizar premios.", faqQ5: "¿Puedo usar el sitio en un móvil o una tableta?", faqA5: "La mayoría de los proyectos están diseñados para navegadores modernos de escritorio y móviles. El diseño y el rendimiento pueden variar según el tamaño de la pantalla, la versión del navegador y las funciones del dispositivo.", faqQ6: "¿Apps & Games utiliza analítica o publicidad?", faqA6: "El sitio utiliza Google Analytics para comprender su uso y puede mostrar publicidad mediante Google AdSense. Encontrarás más información en la", privacyPolicy: "Política de privacidad",
        supportLabel: "ℹ INFO Y SOPORTE", supportHeading: "Apoya el proyecto", supportText1: "Las aplicaciones y los juegos son gratuitos, pero las donaciones voluntarias son bienvenidas.", supportText2: "Una parte de las donaciones recibidas se destinará a distintas organizaciones benéficas. La mayor parte se donará a instituciones que atienden a niños sin un cuidado parental adecuado.", donateHeading: "Puedes donar mediante:", paypalHeading: "Cuenta de PayPal", paypalText: "Apoya el proyecto de forma segura mediante PayPal.", openPayPal: "Abrir PayPal ↗", stripeHeading: "Pago con tarjeta (Stripe)", stripeText: "Dona de forma segura con tarjeta de crédito o débito.", openStripe: "Abrir Stripe ↗", cryptoHeading: "Cartera de criptomonedas", cryptoText: "También puedes apoyar el proyecto con criptomonedas.",
        copy: "Copiar", copied: "¡Copiado!", copyFailed: "Error", learnMore: "MÁS INFORMACIÓN →", openApp: "ABRIR APP →", playGame: "JUGAR →", appBadge: "APP", gameBadge: "JUEGO", live: "ACTIVO", footerAbout: "Acerca de", footerSupport: "Soporte"
    }
};

window.APP_CARD_I18N = {
    en: [
        ["A multifunctional online digital clock with a large display, clean design and useful everyday functionality.", ["Clock", "App", "Online"]],
        ["Generate repeatable lotto number combinations from any selected date with customizable lotto formats and number ranges.", ["Lotto", "Numbers", "Generator"]],
        ["Find emoji meanings by category, copy emojis instantly and paste country flags into Word as real images.", ["Emoji", "Copy & Paste", "Symbols"]],
        ["Convert everyday, technical and digital measurement units quickly across 17 categories and 115 units.", ["Converter", "Measurements", "Tools"]],
        ["Modern Tetris browser game with a stylish neon interface, smooth gameplay and instant play in your browser.", ["Arcade", "Puzzle", "Browser"]],
        ["Defend Earth in a modern neon arcade battle with challenging waves, power-ups, bunkers and instant browser gameplay.", ["Arcade", "Shooter", "Browser"]],
        ["Defend the last star gate in a modern neon arcade shooter with diving Phoenix enemies, collectible power-ups and instant browser play.", ["Arcade", "Shooter", "Power-ups"]]
    ],
    hr: [
        ["Višenamjenski online digitalni sat s velikim prikazom, preglednim dizajnom i korisnim svakodnevnim funkcijama.", ["Sat", "Aplikacija", "Online"]],
        ["Generirajte ponovljive kombinacije loto brojeva iz odabranog datuma uz prilagodljive formate i raspone brojeva.", ["Loto", "Brojevi", "Generator"]],
        ["Pronađite značenja emojija po kategorijama, odmah ih kopirajte i zalijepite zastave država u Word kao prave slike.", ["Emoji", "Kopiranje", "Simboli"]],
        ["Brzo pretvarajte svakodnevne, tehničke i digitalne mjerne jedinice u 17 kategorija i 115 jedinica.", ["Pretvarač", "Mjere", "Alati"]],
        ["Moderna igra Tetris za preglednik s elegantnim neonskim sučeljem, glatkim izvođenjem i trenutnim pokretanjem.", ["Arkadna", "Slagalica", "Preglednik"]],
        ["Branite Zemlju u modernoj neonskoj arkadnoj borbi s izazovnim valovima, bonusima, bunkerima i trenutnim igranjem u pregledniku.", ["Arkadna", "Pucačina", "Preglednik"]],
        ["Branite posljednja zvjezdana vrata u modernoj neonskoj pucačini s Phoenix neprijateljima, bonusima i trenutnim igranjem.", ["Arkadna", "Pucačina", "Bonusi"]]
    ],
    de: [
        ["Eine vielseitige Online-Digitaluhr mit grosser Anzeige, übersichtlichem Design und praktischen Alltagsfunktionen.", ["Uhr", "App", "Online"]],
        ["Erstelle wiederholbare Lottozahlen aus einem gewählten Datum mit anpassbaren Formaten und Zahlenbereichen.", ["Lotto", "Zahlen", "Generator"]],
        ["Finde Emoji-Bedeutungen nach Kategorien, kopiere Emojis sofort und füge Länderflaggen als echte Bilder in Word ein.", ["Emoji", "Kopieren", "Symbole"]],
        ["Wandle Alltags-, Technik- und Dateneinheiten schnell in 17 Kategorien mit 115 Einheiten um.", ["Umrechner", "Einheiten", "Werkzeuge"]],
        ["Modernes Tetris-Browserspiel mit stilvoller Neonoberfläche, flüssigem Spiel und sofortigem Start.", ["Arcade", "Puzzle", "Browser"]],
        ["Verteidige die Erde in einer modernen Neon-Arcade-Schlacht mit anspruchsvollen Wellen, Power-ups und Bunkern.", ["Arcade", "Shooter", "Browser"]],
        ["Verteidige das letzte Sternentor in einem modernen Neon-Shooter gegen Phoenix-Gegner und sammle Power-ups.", ["Arcade", "Shooter", "Power-ups"]]
    ],
    it: [
        ["Un orologio digitale online multifunzione con display grande, design chiaro e utili funzioni quotidiane.", ["Orologio", "App", "Online"]],
        ["Genera combinazioni ripetibili di numeri del lotto da qualsiasi data con formati e intervalli personalizzabili.", ["Lotto", "Numeri", "Generatore"]],
        ["Trova il significato degli emoji per categoria, copiali subito e incolla le bandiere in Word come immagini reali.", ["Emoji", "Copia", "Simboli"]],
        ["Converti rapidamente unità quotidiane, tecniche e digitali in 17 categorie e 115 unità.", ["Convertitore", "Misure", "Strumenti"]],
        ["Tetris moderno per browser con elegante interfaccia al neon, gioco fluido e avvio immediato.", ["Arcade", "Puzzle", "Browser"]],
        ["Difendi la Terra in una moderna battaglia arcade al neon con ondate impegnative, potenziamenti e bunker.", ["Arcade", "Sparatutto", "Browser"]],
        ["Difendi l'ultimo portale stellare in un moderno sparatutto al neon con nemici Phoenix e potenziamenti.", ["Arcade", "Sparatutto", "Potenziamenti"]]
    ],
    es: [
        ["Un reloj digital online multifunción con pantalla grande, diseño claro y útiles funciones cotidianas.", ["Reloj", "App", "Online"]],
        ["Genera combinaciones repetibles de lotería desde cualquier fecha con formatos y rangos personalizables.", ["Lotería", "Números", "Generador"]],
        ["Encuentra significados de emojis por categoría, cópialos al instante y pega banderas en Word como imágenes reales.", ["Emoji", "Copiar", "Símbolos"]],
        ["Convierte rápidamente unidades cotidianas, técnicas y digitales en 17 categorías y 115 unidades.", ["Conversor", "Medidas", "Herramientas"]],
        ["Tetris moderno para navegador con elegante interfaz de neón, juego fluido e inicio instantáneo.", ["Arcade", "Puzle", "Navegador"]],
        ["Defiende la Tierra en una moderna batalla arcade de neón con oleadas, potenciadores y búnkeres.", ["Arcade", "Disparos", "Navegador"]],
        ["Defiende la última puerta estelar en un moderno juego de disparos de neón con enemigos Phoenix y potenciadores.", ["Arcade", "Disparos", "Potenciadores"]]
    ]
};
